import { Product, Review } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "aether-apex-pro",
    name: "Aetheria Apex Pro",
    tagline: "Neural Spatial Audio with Beryllium Planar Drivers",
    category: "Audio",
    price: 499,
    originalPrice: 599,
    rating: 4.96,
    reviewCount: 218,
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?q=80&w=1000&auto=format&fit=crop",
    badge: "FLAGSHIP 2026",
    description: "Equipped with dual neural DSPs and 50mm beryllium planar magnetic transducers. Delivers sub-millisecond head-tracking spatial audio with ultra-wide 5Hz-52kHz acoustic range.",
    specs: ["96-Hour Continuous Battery", "Neural ANC 2.0 (52dB Reduction)", "24-bit/192kHz Lossless Audio", "Aerospace Titanium Chassis"],
    colors: [
      { name: "Obsidian Black", hex: "#171717" },
      { name: "Celestial Silver", hex: "#e5e7eb" },
      { name: "Cyber Violet", hex: "#7c3aed" },
    ],
    inStock: true,
    stockLeft: 14,
    featured: true,
  },
  {
    id: "vision-spatial-band",
    name: "Chronos Halo Spatial Ring",
    tagline: "Continuous Biometric & Spatial Gesture Controller",
    category: "Wearables",
    price: 329,
    originalPrice: 389,
    rating: 4.88,
    reviewCount: 142,
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1000&auto=format&fit=crop",
    badge: "HOT INNOVATION",
    description: "Ultra-compact titanium micro-wearable with 6-axis sub-millimeter gesture tracking, continuous blood-oxygen telemetry, and haptic spatial feedback for VisionOS and holographic displays.",
    specs: ["Grade 5 Polished Titanium", "Sub-millimeter Pinch & Flick Gestures", "10-Day Battery on Magnetic Dock", "Water Resistant to 100M"],
    colors: [
      { name: "Matte Space Gray", hex: "#374151" },
      { name: "Electrum Gold", hex: "#d97706" },
      { name: "Hyper Cobalt", hex: "#2563eb" },
    ],
    inStock: true,
    stockLeft: 23,
    featured: true,
  },
  {
    id: "quantum-desk-rig",
    name: "NovaCore Studio Dock",
    tagline: "Thunderbolt 5 Neural Compute & Gallium Nitride Hub",
    category: "Computing",
    price: 649,
    originalPrice: 749,
    rating: 4.92,
    reviewCount: 96,
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=1000&auto=format&fit=crop",
    badge: "STUDIO GRADE",
    description: "Machined from a single block of bead-blasted aluminum with vapor chamber cooling. Powers triple 8K displays with 180W bi-directional power delivery and an integrated 4TB PCIe Gen 5 NVMe slot.",
    specs: ["Thunderbolt 5 (120 Gbps)", "Triple 8K@120Hz Output", "Built-in 4TB NVMe SSD Bay", "Vapor Chamber Silent Heatsink"],
    colors: [
      { name: "Anodized Silver", hex: "#d1d5db" },
      { name: "Stealth Graphite", hex: "#1f2937" },
    ],
    inStock: true,
    stockLeft: 9,
    featured: true,
  },
  {
    id: "lumina-iris-optics",
    name: "Lumina Iris Vision Glasses",
    tagline: "Micro-OLED Spatial Display with Waveguide Optics",
    category: "Optics",
    price: 899,
    originalPrice: 999,
    rating: 4.95,
    reviewCount: 310,
    image: "https://images.unsplash.com/photo-1508296695146-257a814070b4?q=80&w=1000&auto=format&fit=crop",
    badge: "BEST SELLER",
    description: "Ultra-lightweight 68-gram spatial computing glasses with dual 4K Sony Micro-OLED panels, delivering a massive 200-inch virtual workspace with 120Hz refresh rate and electrochromic dimming.",
    specs: ["Dual 4K Micro-OLED Panels", "Electrochromic Lens Tinting (0-100%)", "68g Featherweight Carbon Fiber", "Directional Spatial Audio Micro-Array"],
    colors: [
      { name: "Carbon Onyx", hex: "#0f172a" },
      { name: "Frosted Glaze", hex: "#e2e8f0" },
      { name: "Emerald Cyber", hex: "#059669" },
    ],
    inStock: true,
    stockLeft: 7,
    featured: true,
  },
  {
    id: "kinetic-hover-drone",
    name: "AeroGlide Whisper 4K",
    tagline: "Autonomous AI Tracking Drone with Silent Toroidal Props",
    category: "Wearables",
    price: 799,
    originalPrice: 899,
    rating: 4.89,
    reviewCount: 84,
    image: "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?q=80&w=1000&auto=format&fit=crop",
    badge: "LIMITED DROP",
    description: "Pocket-sized foldable autonomous creator drone with whisper-quiet toroidal propellers, 360-degree LiDAR obstacle avoidance, and 1-inch CMOS 4K 120fps HDR gimbal.",
    specs: ["Sub-249g Ultralight Compliance", "Whisper-Quiet Toroidal Rotors (48dB)", "45-Min Flight Duration", "360° Solid-State LiDAR Navigation"],
    colors: [
      { name: "Arctic White", hex: "#f9fafb" },
      { name: "Stealth Slate", hex: "#334155" },
    ],
    inStock: true,
    stockLeft: 12,
  },
  {
    id: "prism-audio-sphere",
    name: "Orbital Prism Speaker",
    tagline: "Magnetic Levitation Hi-Res Spatial Monolith",
    category: "Audio",
    price: 379,
    originalPrice: 429,
    rating: 4.85,
    reviewCount: 67,
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?q=80&w=1000&auto=format&fit=crop",
    badge: "DESIGN AWARD",
    description: "A suspended magnetic levitating acoustic orb crafted from acoustic resin and brushed copper, dispersing seamless 360-degree omnidirectional sound with tactile bass resonance.",
    specs: ["True 360° Omnidirectional Sound", "Magnetic Zero-Friction Levitation", "18-Hour Battery with Qi Base", "Qualcomm aptX Adaptive Lossless"],
    colors: [
      { name: "Brushed Bronze", hex: "#78350f" },
      { name: "Pure Ceramic", hex: "#ffffff" },
      { name: "Nebula Purple", hex: "#581c87" },
    ],
    inStock: true,
    stockLeft: 16,
  },
  {
    id: "zenith-keeb-split",
    name: "Zenith Ortho Mechanical Rig",
    tagline: "Ergonomic Split Keyboard with Magnetic Hall-Effect Switches",
    category: "Computing",
    price: 349,
    originalPrice: 399,
    rating: 4.91,
    reviewCount: 175,
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=1000&auto=format&fit=crop",
    badge: "COMMUNITY FAVORITE",
    description: "Wireless split ergonomic aluminum mechanical keyboard with rapid-trigger Hall effect magnetic switches, OLED telemetry displays, and integrated rotary encoders.",
    specs: ["Hall Effect Rapid Trigger (0.1mm)", "Solid CNC Anodized Aluminum 6063", "Dual OLED Live Status Displays", "Tri-Mode (Bluetooth, 2.4G, Type-C)"],
    colors: [
      { name: "Retro Chalk", hex: "#e5e5e5" },
      { name: "Midnight Indigo", hex: "#1e1b4b" },
      { name: "Cyberpunk Pink", hex: "#be185d" },
    ],
    inStock: true,
    stockLeft: 19,
  },
  {
    id: "aura-ambient-cube",
    name: "Aura Lumina Chrono Display",
    tagline: "Synchronous Ambient Smart Lamp with Circadian Engine",
    category: "Smart Home",
    price: 219,
    originalPrice: 269,
    rating: 4.79,
    reviewCount: 94,
    image: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?q=80&w=1000&auto=format&fit=crop",
    badge: "WELLNESS",
    description: "Sculptural glass cube housing 1,024 addressable micro-LEDs that mimics natural atmospheric sunlight and twilight patterns to balance circadian rhythm and productivity.",
    specs: ["1,024 Atmospheric Micro-LEDs", "Auto Circadian Sync via Geolocation", "Air Quality & CO2 Sensor Inside", "Apple HomeKit & Matter Ready"],
    colors: [
      { name: "Smoked Crystal", hex: "#475569" },
      { name: "Opal Diffuser", hex: "#f8fafc" },
    ],
    inStock: true,
    stockLeft: 28,
  },
];

export const CATEGORIES = [
  { id: "Audio", name: "Neural Audio", count: "18 Items", icon: "🎧", description: "Beryllium planar drivers, spatial head-tracking" },
  { id: "Wearables", name: "Spatial Wear", count: "14 Items", icon: "💍", description: "Biometric rings, gesture bands, nano sensors" },
  { id: "Computing", name: "Quantum Computing", count: "12 Items", icon: "⚡", description: "Thunderbolt 5 hubs, Hall-effect split rigs" },
  { id: "Optics", name: "Spatial Optics", count: "8 Items", icon: "👓", description: "Dual 4K micro-OLED, optical waveguides" },
  { id: "Smart Home", name: "Desk Architecture", count: "16 Items", icon: "🏛️", description: "Circadian lighting cubes, magnetic sculptures" },
];

export const REVIEWS: Review[] = [
  {
    id: "rev-1",
    author: "Elena Rostova",
    role: "Lead Hardware Architect, Zurich",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop",
    rating: 5,
    text: "The Aetheria Apex Pro sounds unlike anything I've experienced in 15 years of studio production. The acoustic stage feels physically unbounded, and switching between themes makes the store itself feel like art.",
    productName: "Aetheria Apex Pro",
    verified: true,
  },
  {
    id: "rev-2",
    author: "Marcus Vance",
    role: "Creative Director, Tokyo",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop",
    rating: 5,
    text: "The Chronos Halo Ring paired with Iris Optics completely replaced my laptop during international flights. Unbelievable tactile feedback and zero latency spatial gesture response.",
    productName: "Chronos Halo Spatial Ring",
    verified: true,
  },
  {
    id: "rev-3",
    author: "Dr. Aris Thorne",
    role: "Acoustic Engineering Fellow",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop",
    rating: 5,
    text: "Exceptional build quality. The titanium CNC machining and thermal dissipation on the NovaCore dock are flawless. True benchmark grade hardware.",
    productName: "NovaCore Studio Dock",
    verified: true,
  },
];

export const AI_PRESETS = [
  {
    id: "minimal",
    title: "Minimalist Executive",
    tagline: "Stark monochrome precision with maximum signal-to-noise ratio",
    icon: "◻️",
    products: ["NovaCore Studio Dock", "Zenith Ortho Mechanical Rig"],
    bundlePrice: 899,
    savings: 99,
    themeMatch: "minimalism",
  },
  {
    id: "cyber",
    title: "Cyberpunk Battlestation",
    tagline: "High-octane neon aesthetics with low latency tactile controls",
    icon: "⚡",
    products: ["Aetheria Apex Pro", "Zenith Ortho Mechanical Rig"],
    bundlePrice: 749,
    savings: 99,
    themeMatch: "maximalism",
  },
  {
    id: "spatial",
    title: "Visionary Spatial Nomad",
    tagline: "Boundless virtual workspaces anywhere on Earth",
    icon: "🥽",
    products: ["Lumina Iris Vision Glasses", "Chronos Halo Spatial Ring"],
    bundlePrice: 1099,
    savings: 129,
    themeMatch: "spatial-ui",
  },
  {
    id: "zen",
    title: "Acoustic Zen Sanctuary",
    tagline: "Circadian lighting and pure harmonic 360-degree sound",
    icon: "🍃",
    products: ["Orbital Prism Speaker", "Aura Lumina Chrono Display"],
    bundlePrice: 529,
    savings: 69,
    themeMatch: "skeuomorphism",
  },
];
